### PR TITLE
Refresh pass to remove custom decryption and token validation

### LINKED ISSUE #198: Remove custom token validation code once SDK supports v2
As described in #170 replace custom token validation code once https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/317 is fixed.

@baywet

### LINKED ISSUE #335: deserializtion of notifications fails because no deserialization provider is registered
here 
https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/9be538d386f941ecfa675c902cb596ae42d7a8ea/src/GraphWebhooks/Controllers/ListenController.cs#L76
and there
https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/9be538d386f941ecfa675c902cb596ae42d7a8ea/src/GraphWebhooks/Controllers/LifecycleController.cs#L54

The following line needs to be added
```csharp
ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
```

### PR DESCRIPTION
**Pull request by jasonjoh**
- Cleaned up README and supporting files
- Deleted outdated localized README files
- Removed custom payload decryption code
- Removed custom token validation code (Fixes #198)
- Added call to `RegisterDefaultDeserializer` calls (Fixes #335)
- Added StyleCop and fixed all violations

### CODE REVIEW

File: src/GraphWebhooks/Controllers/HomeController.cs [hunk 1]
```diff
@@ -2,23 +2,38 @@
...
 
+/// <summary>
+/// The controller for the home page.
+/// </summary>
 public class HomeController : Controller
 {
+    /// <summary>
+    /// Initializes a new instance of the <see cref="HomeController"/> class.
+    /// </summary>
+    public HomeController()
```
Comment (baywet) [inline src/GraphWebhooks/Controllers/HomeController.cs:19]: this could have been a primary constructor as well for consistency

File: src/GraphWebhooks/Startup.cs [hunk 2]
```diff
@@ -81,21 +97,28 @@ public void ConfigureServices(IServiceCollection services)
...
+    /// </summary>
+    /// <param name="app">The application builder provided by the runtime.</param>
+    /// <param name="env">The web host environment provided by the runtime.</param>
+    /// <exception cref="ArgumentException">Thrown if any parameter is null.</exception>
     public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
     {
-        _ = app ?? throw new ArgumentException(nameof(app));
-        _ = env ?? throw new ArgumentException(nameof(env));
+        _ = app ?? throw new ArgumentException("IApplicationBuilder cannot be null", nameof(app));
+        _ = env ?? throw new ArgumentException("IWebHostEnvironment cannot be null", nameof(env));
```
Comment (baywet) [inline src/GraphWebhooks/Startup.cs:122]: I'm not sure this change is helpful?
Instead of giving you the parameter name, it'll give you the type in the exception message

**Review by baywet — DISMISSED** [review]

File: src/GraphWebhooks/Controllers/HomeController.cs (hunk 1 above)
Comment (jasonjoh) [reply src/GraphWebhooks/Controllers/HomeController.cs:19]: Good catch

File: src/GraphWebhooks/Startup.cs (hunk 2 above)
Comment (jasonjoh) [reply src/GraphWebhooks/Startup.cs:122]: It was complaining that I didn't use this form (https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208).

I just tested it, and the message becomes `IApplicationBuilder cannot be null (Parameter 'app')`

**Review by baywet — APPROVED** [review]
